---
title: "GBTM baseline covariates"
date: "6/15/2020"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
library(tidyverse)
library(knitr)
library(readxl)
library(openxlsx)
library(data.table)
library(Hmisc)
```


**Baseline covariates to use: AGE_ADMISSION, FEMALE, RACE, TOBACCO_STATUS_LABEL, HOSP_ROLLUP_GROUPING**



```{r}
static.features <- read_excel("~/Desktop/datasets/processed/Static Characteristics.xlsx", sheet = 'static')
series.df <- read_excel('~/Desktop/datasets/processed/GBTM_data/combined gbtm data v2.xlsx', sheet = 'Sheet 1')
baseline.df <- read_excel('~/Desktop/datasets/processed/GBTM_data/Filtered Baseline imputed.xlsx', sheet = 'Sheet 1')
```



```{r}
patients_id <- unique(series.df$patients.id)
covariates.df.2 <- baseline.df[which(baseline.df$rID %in% patients_id),] %>% select(col.list.2)
covariates.df.1 <- static.features[which(static.features$rID %in% patients_id),] %>% select(col.list.1)
```



**Which covariates to use? **



```{r}
# change_col_names <- function(measure_name){
#   col_names <- c()
#   for (val in seq(1,length(colnames(covariates.df.1)))){
#     col_names <- append(col_names, paste(measure_name, val, sep="_"))
#   }
#   return(col_names)
# }
# 
# names(covariates.df.1) <- change_col_names('STATIC')

```




# save dataset




```{r}
combined.baseline <- cbind(series.df, covariates.df.1, covariates.df.2)
write.xlsx(combined.baseline, '~/Desktop/datasets/processed/GBTM_data/combined gbtm data v3.xlsx', col.names = TRUE, row.names = FALSE)
```



