---
title: "GBTM baseline covariates"
date: "6/15/2020"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
library(tidyverse)
library(knitr)
library(readxl)
library(openxlsx)
library(data.table)
library(Hmisc)
```


**Baseline covariates to use: AGE_ADMISSION, FEMALE, RACE, TOBACCO_STATUS_LABEL, HOSP_ROLLUP_GROUPING**



```{r}
series.df <- read_excel('~/Desktop/datasets/processed/GBTM_data/combined gbtm stata data v2.xlsx', sheet = 'Sheet 1')
baseline.df <- read_excel("/Users/jinchenxie/Desktop/datasets/processed/GBTM_data/gbtm Cohort data combined.xlsx", sheet = 'baseline')
series.df.2 <- read_excel('~/Desktop/datasets/processed/GBTM_data/combined gbtm stata data v4.xlsx', sheet = 'Sheet 1')
# admission.df <- read_excel("/Users/jinchenxie/Desktop/datasets/processed/GBTM_data/gbtm Cohort data combined.xlsx", sheet = "admission")
admission.relevant <- read_excel('~/Desktop/datasets/processed/admission_procedure_everflags.xlsx', sheet = 'Sheet 1')
```

# save dataset
```{r}
full.df <- cbind(baseline.df, admission.relevant[,-1])
covariates.df <- full.df %>% select(all_of(list.attris))
```


```{r}
# write.xlsx(admission.relevant, "~/Desktop/datasets/processed/baseline_procedure_everflags.xlsx", col.names = TRUE, row.names = FALSE)
```


```{r}
combined.baseline <- cbind(series.df.2, covariates.df)
write.xlsx(combined.baseline, '~/Desktop/datasets/processed/GBTM_data/combined gbtm stata data v5.xlsx', col.names = TRUE, row.names = FALSE)

```



