---
title: "traj groups profiling 2"
output: html_notebook
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
library(readxl)
library(tidyverse)
```


# import data
```{r}
df <- read_excel("~/Desktop/trial save.xlsx", sheet="Sheet1")
baseline.df <- read_excel("~/Desktop/datasets/processed/Filtered Attributes Baseline.xlsx", sheet = 'updated_folup_NA30_baseline')
```


# attributes need to be assessed
```{r}
attris.df <- baseline.df[which(baseline.df$rID %in% df$patientsid),]
attris.df <- attris.df %>% select(starts_with("BP_"), "PULSE", "BMI", ends_with("_00"), "CTB") 
summary(attris.df)
```
# identify patients in each traj group
```{r}
groups <- sort(unique(df$`_traj_Group`))
pat.membership <- vector(mode="list", length = length(groups))
for (group in groups){
  pat.membership[[group]] <- df$patientsid[which(df$`_traj_Group`==group)]
}
```



**Examine if any group has a significantly large portion of missing value (BP_SYSTOLIC, BP_DIASTOLIC, PULSE, BMI)**
```{r}
na.attris.list <- c("BP_SYSTOLIC", "BP_DIASTOLIC", "PULSE", "BMI")

na.profile.df <- data.frame(row.names = groups)

for (group in groups){
  temp_len <- length(pat.membership[[group]])
  for (k in 1:length(na.attris.list)){
    na.profile.df[group, na.attris.list[k]] <- dim(baseline.df[which
                                                               (baseline.df$rID %in% pat.membership[[group]] & 
                                                                is.na(baseline.df[[na.attris.list[k]]])),]
                                                                )[1]/temp_len
    if (na.profile.df[group, na.attris.list[k]]>=0.5){
      print("Attention Here!!")
    }
  }
}
```

**Use complete cases for mean value**

```{r}
attributes.list <- colnames(attris.df)
profile.df <- data.frame(row.names = groups)




for (group in groups){
  k <- 1
  for (attri in attributes.list){
    if (k<5){
      profile.df[group, attri] <- mean(baseline.df[[attri]][which(baseline.df$rID %in% pat.membership[[group]])], na.rm = TRUE)
      profile.df[group, paste0("std_", attri)] <- sd(baseline.df[[attri]][which(baseline.df$rID %in% pat.membership[[group]])], na.rm = TRUE)
      profile.df[group, paste0("%na_", attri)] <- dim(baseline.df[which
                                                               (baseline.df$rID %in% pat.membership[[group]] & 
                                                                is.na(baseline.df[[attri]])),]
                                                                )[1]/length(pat.membership[[group]])
    }else{
      profile.df[group, attri] <- sum(baseline.df[[attri]][which(baseline.df$rID %in% pat.membership[[group]])], na.rm = TRUE)/length(pat.membership[[group]])
    }
    k <- k+1
  } 
}
```


```{r}
full.prof.df <- data.frame(row.names = 1)

k <- 1
for (attri in attributes.list){
  if (k<5){
    full.prof.df[1, attri] <- mean(attris.df[[attri]], na.rm = TRUE)
    full.prof.df[1, paste0("std_", attri)] <- sd(attris.df[[attri]], na.rm = TRUE)
    full.prof.df[1, paste0("%na_", attri)] <- dim(attris.df[which(is.na(attris.df[[attri]])),])[1]/dim(attris.df)[1]
  }else{
    full.prof.df[1, attri] <- sum(attris.df[[attri]], na.rm = TRUE)/dim(attris.df)[1]
  }
  k <- k+1
}
```


```{r}
col.cov.2 <- colnames(attris.df)
```



# save dataset
```{r}
write.xlsx(profile.df, '~/Desktop/traj profile 2.xlsx', col.names = TRUE, row.names = FALSE)
write.xlsx(full.prof.df, '~/Desktop/traj profile all.xlsx', col.names = TRUE, row.names = FALSE)
```



